
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mysql:
    image: mysql:5.7.24
    environment:
      - MYSQL_DATABASE=recognizer_test
      - MYSQL_ROOT_PASSWORD=recognizer
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci

    ports:
      - "3306:3306"
    volumes:
      - /home/yongjinchong/dev/cosmic/recognizer/mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  ## MinIO (S3)
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /home/yongjinchong/dev/cosmic/cosmic-sync/data --console-address ":9001"
    volumes:
      - minio-data:/home/yongjinchong/dev/cosmic/cosmic-sync/data


  ## Moto Server
  moto:
    image: motoserver/moto
    container_name: moto
    ports:
      - "5000:5000"

  # ## LocalStack
  # localstack:
  #   image: localstack/localstack
  #   container_name: localstack
  #   ports:
  #     - "4566:4566"  # LocalStack
  #   environment:
  #     - SERVICES=s3
  #     - DEFAULT_REGION=us-east-1
  #     - DEBUG=1
  #   volumes:
  #     - localstack-data:/var/lib/localstack
  #     - /var/run/docker.sock:/var/run/docker.sock

  # ## OpenStack Swift (S3 API via Swift3 Middleware)
  # swift:
  #   image: openstackswift/swift-all-in-one
  #   container_name: swift
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SWIFT_DEFAULT_USER=test:tester
  #     - SWIFT_DEFAULT_KEY=testing
  #     - SWIFT_DEFAULT_TENANT=test
  #   volumes:
  #     - swift-data:/srv
  #   privileged: true

volumes:
  minio-data:
  # localstack-data:
  # swift-data: